name: Single Instance Tests

on: [push, pull_request]

jobs:
  single-instance-on-default-port:
    name: MongoDB v${{ matrix.mongodb-version }} — Node.js v${{ matrix.node-version }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22]
        mongodb-version: ['5.0', '6.0', '7.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start MongoDB Server v${{ matrix.mongodb-version }}
        uses: ./
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test ./test/single-instance
        env:
          CI: true
          MONGODB_DB: ${{ matrix.mongodb-db }}


  single-instance-on-custom-port:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-port: [12345]
        mongodb-version: ['5.0', '6.0', '7.0']
        node-version: [20, 22]

    name: MongoDB v${{ matrix.mongodb-version }}, Port ${{ matrix.mongodb-port }} — Node.js v${{ matrix.node-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start MongoDB Server v${{ matrix.mongodb-version }}
        uses: ./
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-port: ${{ matrix.mongodb-port }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test ./test/custom-port
        env:
          CI: true
